# Generated by Django 3.1.1 on 2020-10-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200930_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createprofile',
            old_name='profile',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='createprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='createprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='createprofile',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='profile_imgs'),
        ),
    ]
