# Generated by Django 3.1.1 on 2020-10-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20201022_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='category',
            field=models.CharField(choices=[('twin', 'Villa Bor'), ('dbl', 'Vila Ela'), ('fam', 'Villa Arka'), ('dsui', 'Villa Aspen'), ('apt', 'Villa Iris'), ('dapt', 'Villa Alagen')], max_length=25),
        ),
    ]
