# Generated by Django 3.1.1 on 2020-10-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20201001_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_profile',
        ),
    ]
